Completed prep-css-flexbox. Paul Son
contactpaulson/prep-1121-code-solutions pull request #8
Opened 2021-11-12 05:26 UTC by contactpaulson

![prep-css-flexbox display-flex](https://user-images.githubusercontent.com/93624324/141414568-14dbb441-5fca-4f30-a5ed-72914e72cfc4.png
![prep-css-flexbox flex-wrap](https://user-images.githubusercontent.com/93624324/141414612-6a2705a0-289d-478c-895f-6615ef18a83f.png)
![prep-css-flexbox justify-content](https://user-images.githubusercontent.com/93624324/141414644-821b3bd2-fa9c-427a-b951-4316715aaf2c.png)
)
![prep-css-flexbox align-items](https://user-images.githubusercontent.com/93624324/141414654-a6d7f4e4-118e-42d8-a9a0-31a07c49ad01.png)

2021-11-12 23:43 UTC, thebearingedge requested changes
great, just a couple small changes

2021-11-12 23:43 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +        flex-basis: calc(100% / 3);
Careful `flex-basis` goes on flex items (children of elements with `display: flex`). You can add another rule set with a selector for `.card-container` and apply the `flex-basis` there.

2021-11-12 23:43 UTC, thebearingedge commented on prep-css-flexbox/justify-content.html
> +        flex-basis: 25%;
Same here, try putting the `flex-basis` on the `.card-container`.

2021-11-13 00:31 UTC, contactpaulson commented
![prep-css-flexbox display-flex](https://user-images.githubusercontent.com/93624324/141598278-94dbe3f1-9ded-41bc-8cb2-542a35344230.png
![prep-css-flexbox flex-wrap](https://user-images.githubusercontent.com/93624324/141598294-0cf30d8f-8963-4240-af8a-8b9f8709f170.png)
![prep-css-flexbox justify-content](https://user-images.githubusercontent.com/93624324/141598322-383e9dda-0c1b-4f5a-9a0d-1511b452ebfe.png)
)
![prep-css-flexbox align-items](https://user-images.githubusercontent.com/93624324/141598329-af66cee9-9988-422e-9076-2e9bbab505b9.png)

2021-11-13 18:00 UTC, contactpaulson commented
![prep-css-flexbox display-flex](https://user-images.githubusercontent.com/93624324/141654233-912e1087-1b1a-4844-8603-019d31a55abc.png
![prep-css-flexbox flex-wrap](https://user-images.githubusercontent.com/93624324/141654244-b5d5c918-df10-4e3c-9732-737d34e2e2ea.png)
![prep-css-flexbox justify-content](https://user-images.githubusercontent.com/93624324/141654251-f9f144e6-bc0d-49a6-a397-9059a9cd349b.png)
)
![prep-css-flexbox align-items](https://user-images.githubusercontent.com/93624324/141654258-c03a5733-8d92-45f3-a53b-50d6eb29ff87.png)

2021-11-13 19:25 UTC, thebearingedge approved these changes
got it!

2021-11-14 06:02 UTC, merged